version: '3'
services:
  mongo:
    image: mongo
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./app/node_modules
      - ./client:/app
    # polling setting for Docker. activate auto reload when file change.
    environment:
      - CHOKIDAR_USEPOLLING=true
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      - ./app/node_modules
      - ./node:/app
