// todo
export const SET_TODO_LIST = 'SET_TODO_LIST';
export const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED';
export const ADD_TODO = 'ADD_TODO';
export const ON_CARD_CLICKED = 'ON_CARD_CLICKED';

// master
export const CREATE_TODO_MASTER = 'CREATE_TODO_MASTER';
export const SET_TODO_MASTER_LIST = 'SET_TODO_MASTER_LIST';
export const ON_MSTER_CARD_CLICKED = 'ON_MSTER_CARD_CLICKED';

// complete
export const ADD_COMPLETE = 'ADD_COMPLETE';
export const ON_COMPLETE = 'ON_COMPLETE';
export const ON_INIT_COMPLETE_LIST = 'ON_INIT_COMPLETE_LIST';
export const SET_COMPLETE_LIST = 'SET_COMPLETE_LIST';
export const FETCH_COMPLETE_FAILED = 'FETCH_COMPLETE_FAILED';
