export const SET_TODO_LIST = 'SET_TODO_LIST';
export const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED';
export const CREATE_TODO_MASTER = 'CREATE_TODO_MASTER';
export const ADD_TODO = 'ADD_TODO';
export const SET_TODO_MASTER_LIST = 'SET_TODO_MASTER_LIST';
